version: 2.1
executors:
    base-executor:
        working_directory: ~/listery
        docker:
            - image: circleci/python:2.7.15-stretch-node-browsers
commands:
    javascript_setup:
        description: "Set up JavaScript code"
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            - run:
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    python_setup:
        description: "Set up Python code"
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
            - run:
                command: sudo pip install pipenv
            - restore_cache:
                keys:
                    # when lock file changes, use increasingly general patterns to restore cache
                    - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                    - pip-packages-v1-{{ .Branch }}-
                    - pip-packages-v1-
            - run:
                command: pipenv install
            - run:
                command: pipenv install -r requirements_testing.txt --dev
            - save_cache:
                paths:
                    - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
                key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
jobs:
    javascript:
        executor: base-executor
        steps:
            - javascript_setup
            - run: mkdir -p ~/reports/jest ~/reports/eslint
            - run:
                name: Set up environment variable
                command: echo 'export JEST_JUNIT_OUTPUT=~/reports/jest/test-results.xml' >> $BASH_ENV
            - run:
                name: Install JUnit coverage reporter
                command: npm install jest-junit --save-dev
            - run:
                name: Run tests with JUnit as reporter
                command: npm run test -- --ci --reporters=default --reporters=jest-junit
            - run: ./node_modules/.bin/eslint assets/ --format junit --output-file ~/reports/eslint/test-results.xml
            - store_test_results:
                path: ~/reports
            - store_artifacts:
                path: ~/reports
    python:
        executor: base-executor
        steps:
            - python_setup
            - run: mkdir -p ~/reports/django ~/reports/pylint
            - run:
                command: pipenv run pytest --junitxml=~/reports/django/test-results.xml
            - run:
                command: pipenv run pytest --pylint --pylint-rcfile=.pylintrc listery --junitxml=~/reports/pylint/test-results.xml
            - store_test_results:
                path: ~/reports
            - store_artifacts:
                path: ~/reports
workflows:
    version: 2.1
    test_in_parallel:
        jobs:
            - javascript
            - python
