# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('listery', '0002_auto_20151031_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='show_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
